// Moji: on-device text -> emoji suggestions for Kotlin Multiplatform. Pure Kotlin inference,
// model bundled in the library, zero runtime dependencies.
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Base64

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.vanniktech.mavenPublish)
}

/**
 * Writes files as base64 chunks into a Kotlin object, `files: Map<name, Array<String>>`.
 * Used for the model on targets without jar resources, and for the test vectors in commonTest.
 */
abstract class EmbedFilesTask : DefaultTask() {
    @get:InputFiles @get:PathSensitive(PathSensitivity.NAME_ONLY) abstract val sources: ConfigurableFileCollection
    @get:Input abstract val objectName: Property<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val chunk = 60_000 // multiple of 4, well under the 64K string-literal limits
        val out = StringBuilder()
        out.append("// GENERATED by the ${name} task from ${sources.files.joinToString { it.name }}. Do not edit.\n")
        out.append("package io.github.rajumark.hoverfly.moji.internal\n\n")
        out.append("internal object ${objectName.get()} {\n")
        out.append("    val files: Map<String, Array<String>> by lazy {\n        mapOf(\n")
        for (f in sources.files.sortedBy { it.name }) {
            val b64 = Base64.getEncoder().encodeToString(f.readBytes())
            out.append("            \"${f.name}\" to arrayOf(\n")
            for (i in b64.indices step chunk) out.append("                \"").append(b64, i, minOf(b64.length, i + chunk)).append("\",\n")
            out.append("            ),\n")
        }
        out.append("        )\n    }\n}\n")
        val dir = outputDir.get().asFile.resolve("io/github/rajumark/hoverfly/moji/internal")
        dir.deleteRecursively(); dir.mkdirs()
        dir.resolve("${objectName.get()}.kt").writeText(out.toString())
    }
}

val modelDir = layout.projectDirectory.dir("src/modelData")
val embedModel = tasks.register<EmbedFilesTask>("generateEmbeddedModel") {
    sources.from(modelDir.dir("io/github/rajumark/hoverfly/moji/model").asFileTree)
    objectName = "EmbeddedModel"
    outputDir = layout.buildDirectory.dir("generated/embeddedModel/kotlin")
}
val embedTestVectors = tasks.register<EmbedFilesTask>("generateTestVectors") {
    sources.from(layout.projectDirectory.file("src/commonTest/testData/testvectors.tsv"))
    objectName = "TestData"
    outputDir = layout.buildDirectory.dir("generated/testData/kotlin")
}

kotlin {
    explicitApi()

    jvm {
        compilerOptions { jvmTarget = JvmTarget.JVM_1_8 }
    }
    android {
        namespace = "io.github.rajumark.hoverfly.moji"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        withHostTestBuilder {}.configure {}
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }.configure {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }

        compilerOptions { jvmTarget = JvmTarget.JVM_1_8 }
    }
    iosArm64()
    iosSimulatorArm64()
    macosArm64()
    js {
        browser { testTask { useKarma { useChromeHeadless() } } }
        nodejs { testTask { useMocha { timeout = "120s" } } }
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser { testTask { useKarma { useChromeHeadless() } } }
        nodejs { testTask { useMocha { timeout = "120s" } } }
    }

    // "embedded" = targets without jar resources (Apple + web): they get the model compiled in.
    applyDefaultHierarchyTemplate {
        common {
            group("embedded") {
                group("apple")
                group("web")
            }
        }
    }

    sourceSets {
        commonTest {
            kotlin.srcDir(embedTestVectors.map { it.outputDir })
            dependencies { implementation(libs.kotlin.test) }
        }
        getByName("embeddedMain").kotlin.srcDir(embedModel.map { it.outputDir })
        jvmMain { resources.srcDir(modelDir) }
        androidMain { resources.srcDir(modelDir) }
        getByName("androidDeviceTest").dependencies {
            implementation("androidx.test:runner:1.7.0")
            implementation("androidx.test.ext:junit:1.3.0")
        }
    }
}

// Coordinates and POM come from gradle.properties; credentials and the signing key from
// ~/.gradle/gradle.properties. Nothing here uploads unless a *MavenCentral* task is run.
mavenPublishing {
    publishToMavenCentral()
    if (providers.gradleProperty("signingInMemoryKey").isPresent) signAllPublications()
}
