// GENERATED by scripts/GenTables.java from the JDK's Character data (JDK 26.0.2.1). Do not edit.
package io.github.rajumark.hoverfly.moji.internal

/** Inclusive code point ranges, flattened [start0, end0, start1, end1, ...], base-36 encoded. */
internal object UnicodeTables {
    /** Letters (L*) and numbers (Nd, Nl, No), plus '_': 779 ranges. */
    val WORD: IntArray = decode(
        "1c,1l,1t,2i,2n,2n,2p,3e,4q,4q,4y,4z,51,51,55,56,58,5a,5c,5y,60,6u,6w,jl,jq,k1,kg,kk,ks,ks,ku,ku,og,o" +
        "k,om,on,oq,ot,ov,ov,p2,p2,p4,p6,p8,p8,pa,pt,pv,s5,s7,w1,wa,10v,10x,11y,121,121,128,13c,15c,162,167,1" +
        "6a,17k,18q,19c,19l,19q,19r,19t,1cj,1cl,1cl,1d1,1d2,1da,1do,1dr,1dr,1e8,1e8,1ea,1f3,1fx,1id,1ip,1ip,1" +
        "j4,1ka,1kk,1kl,1kq,1kq,1kw,1lh,1lm,1lm,1lw,1lw,1m0,1m0,1mo,1nc,1nk,1nu,1o0,1on,1op,1ov,1pc,1qh,1s4,1" +
        "tl,1tp,1tp,1u8,1u8,1ug,1up,1uu,1v3,1v5,1vk,1vp,1vw,1vz,1w0,1w3,1wo,1wq,1ww,1wy,1wy,1x2,1x5,1x9,1x9,1" +
        "xq,1xq,1y4,1y5,1y7,1y9,1ye,1yp,1ys,1yx,1z0,1z0,1z9,1ze,1zj,1zk,1zn,208,20a,20g,20i,20j,20l,20m,20o,2" +
        "0p,21l,21o,21q,21q,21y,227,22a,22c,22t,231,233,235,237,23s,23u,240,242,243,245,249,24d,24d,24w,24w,2" +
        "5c,25d,25i,25r,261,261,26d,26k,26n,26o,26r,27c,27e,27k,27m,27n,27p,27t,27x,27x,28s,28t,28v,28x,292,2" +
        "9b,29d,29j,29v,29v,29x,2a2,2a6,2a8,2aa,2ad,2ah,2ai,2ak,2ak,2am,2an,2ar,2as,2aw,2ay,2b2,2bd,2c0,2c0,2" +
        "cm,2cy,2dh,2do,2dq,2ds,2du,2eg,2ei,2ex,2f1,2f1,2fs,2fu,2fw,2fx,2g0,2g1,2g6,2gf,2go,2gu,2gw,2gw,2h1,2" +
        "h8,2ha,2hc,2he,2i0,2i2,2ib,2id,2ih,2il,2il,2jg,2ji,2jk,2jl,2jq,2jz,2k1,2k2,2kk,2ks,2ku,2kw,2ky,2m2,2" +
        "m5,2m5,2mm,2mm,2ms,2mu,2mw,2n5,2na,2ns,2nu,2nz,2o5,2om,2oq,2pd,2pf,2pn,2pp,2pp,2ps,2py,2qu,2r3,2rl,2" +
        "sw,2sy,2sz,2tc,2ti,2ts,2u1,2v5,2v6,2v8,2v8,2va,2ve,2vg,2w3,2w5,2w5,2w7,2wg,2wi,2wj,2wt,2wt,2ww,2x0,2" +
        "x2,2x2,2xc,2xl,2xo,2xr,2yo,2yo,2zk,303,30g,30n,30p,31o,32g,32k,35s,36y,37j,37t,380,385,38a,38d,38h,3" +
        "8h,38l,38m,38u,38w,391,39d,39q,39q,39s,3a1,3a8,3b9,3bb,3bb,3bh,3bh,3bk,3cq,3cs,3m0,3m2,3m5,3m8,3me,3" +
        "mg,3mg,3mi,3ml,3mo,3ns,3nu,3nx,3o0,3ow,3oy,3p1,3p4,3pa,3pc,3pc,3pe,3ph,3pk,3py,3q0,3rk,3rm,3rp,3rs,3" +
        "tm,3u1,3uk,3uo,3v3,3vk,3xx,3y0,3y5,3y9,4fg,4fj,4fz,4g1,4gq,4gw,4iy,4j2,4jc,4jk,4k1,4kf,4kx,4lc,4lt,4" +
        "m8,4mk,4mm,4mo,4n4,4oj,4pj,4pj,4po,4po,4ps,4q1,4q8,4qh,4r4,4rd,4rk,4u0,4u8,4uc,4uf,4vc,4ve,4ve,4vk,4" +
        "xh,4xs,4ym,4zq,50t,50w,510,51c,52j,52o,53d,53k,53u,54w,55i,55s,578,58g,58p,58w,595,59j,59j,5c5,5df,5" +
        "dx,5e4,5e8,5eh,5fn,5gg,5gu,5id,5j4,5k3,5kw,5l5,5l9,5ml,5mo,5my,5n4,5oa,5od,5of,5pl,5po,5pq,5pv,5px,5" +
        "py,5q2,5q2,5q8,5vj,5xc,651,654,659,65c,66d,66g,66l,66o,66v,66x,66x,66z,66z,671,671,673,67x,680,69g,6" +
        "9i,69o,69q,69q,69u,69w,69y,6a4,6a8,6ab,6ae,6aj,6ao,6b0,6b6,6b8,6ba,6bg,6eo,6ep,6es,6ex,6f3,6fd,6fk,6" +
        "fw,6iq,6iq,6iv,6iv,6iy,6j7,6j9,6j9,6jd,6jh,6jo,6jo,6jq,6jq,6js,6js,6ju,6jx,6jz,6k9,6kc,6kf,6kl,6kp,6" +
        "ku,6ku,6kw,6mh,76o,78b,7ai,7b3,7sm,7tf,8ow,8v8,8vf,8vi,8vm,8vn,8vx,8vx,8w0,8x1,8x3,8x3,8x9,8x9,8xc,8" +
        "yv,8z3,8z3,8zk,906,90g,90m,90o,90u,90w,912,914,91a,91c,91i,91k,91q,91s,91y,920,926,94f,94f,9hh,9hj,9" +
        "i9,9ih,9ip,9it,9iw,9j0,9j5,9li,9lp,9lr,9lt,9oa,9oc,9of,9ol,9pr,9pt,9se,9si,9sl,9sw,9tr,9v4,9vj,9wg,9" +
        "wp,9xk,9xr,9xt,9y7,9z4,9zd,a0h,a0v,a9s,fcv,feo,wi4,wk0,wl9,wlc,wss,wsw,wtn,wu8,wvi,wvz,wwt,www,wz3,x" +
        "07,x0f,x0i,x3c,x3f,x5o,x69,x6p,x6r,x6t,x6v,x6y,x70,x7m,x80,x85,x8g,x9v,xaa,xbn,xcg,xcp,xde,xdj,xdn,x" +
        "dn,xdp,xdq,xds,xet,xf4,xfq,xgg,xh8,xhg,xiq,xjj,xjt,xk0,xk4,xk6,xku,xkw,xm0,xmo,xmq,xms,xmz,xn4,xnd,x" +
        "nk,xo6,xoa,xoa,xoe,xpr,xpt,xpt,xpx,xpy,xq1,xq5,xq8,xq8,xqa,xqa,xqz,xr1,xr4,xre,xrm,xro,xs1,xs6,xs9,x" +
        "se,xsh,xsm,xsw,xt2,xt4,xta,xtc,xui,xuk,xux,xv4,xya,xyo,xyx,xz4,16lf,16ls,16me,16mj,16nv,1d6o,1dgt,1d" +
        "gw,1djt,1dkw,1dl2,1dlf,1dlj,1dlp,1dlp,1dlr,1dm0,1dm2,1dme,1dmg,1dmk,1dmm,1dmm,1dmo,1dmp,1dmr,1dms,1d" +
        "mu,1dpt,1dqr,1e0t,1e1c,1e33,1e36,1e4n,1e5s,1e63,1e9c,1e9g,1e9i,1ed8,1eds,1ee1,1ee9,1eey,1ef5,1efu,1e" +
        "g6,1eim,1eiq,1eiv,1eiy,1ej3,1ej6,1ejb,1eje,1ejg,1ekg,1ekr,1ekt,1eli,1elk,1em2,1em4,1em5,1em7,1eml,1e" +
        "mo,1en1,1eo0,1ere,1err,1esz,1etc,1euw,1eve,1evf,1f28,1f30,1f34,1f4g,1f4x,1f5n,1f5s,1f6r,1f71,1f7u,1f" +
        "80,1f91,1f9c,1fa5,1fa8,1fb7,1fbc,1fbj,1fbl,1fbp,1fcw,1fh9,1fhc,1fhl,1fhs,1fir,1fiw,1fjv,1fk0,1fl3,1f" +
        "lc,1fmr,1fn4,1fne,1fng,1fnu,1fnw,1fo2,1fo4,1fo5,1fo7,1foh,1foj,1fox,1foz,1fp5,1fp7,1fp8,1fpc,1fqr,1f" +
        "r4,1fzq,1g00,1g0l,1g0w,1g13,1g1s,1g1x,1g1z,1g34,1g36,1g3e,1g5c,1g5h,1g5k,1g5k,1g5m,1g6t,1g6v,1g6w,1g" +
        "70,1g70,1g73,1g7p,1g7s,1g8m,1g8p,1g9q,1g9z,1ga7,1gbk,1gc2,1gc4,1gc5,1gcb,1gd7,1gdc,1ge1,1ge8,1gex,1g" +
        "g0,1ghj,1gho,1gi7,1gia,1gjk,1gk0,1gk3,1gk5,1gk7,1gk9,1gl1,1glc,1glk,1gm8,1gn2,1gn4,1gnz,1gow,1gp3,1g" +
        "p5,1gpw,1gq3,1gq7,1gqo,1gs5,1gsg,1gt1,1gt4,1gtu,1gu0,1gup,1gvd,1gvj,1gxs,1gzs,1h1c,1h2q,1h34,1h4i,1h" +
        "4q,1h5v,1h68,1h6h,1h6o,1h7p,1h7z,1h8l,1heo,1hfi,1hfk,1hgp,1hgw,1hgx,1hhe,1hhj,1hj4,1hk7,1hkg,1hl1,1h" +
        "ld,1hlg,1hm8,1hmp,1ho0,1hor,1hpc,1hpy,1hqb,1hrr,1hsi,1htb,1htd,1hte,1hth,1hth,1htv,1hv3,1hw0,1hwo,1h" +
        "ww,1hx5,1hxf,1hye,1hyu,1hz3,1hz8,1hz8,1hzb,1hzb,1hzk,1i0i,1i0m,1i0m,1i0z,1i2a,1i2p,1i2s,1i34,1i3e,1i" +
        "3g,1i3g,1i3l,1i44,1i4g,1i4x,1i4z,1i5n,1i67,1i68,1i80,1i86,1i88,1i88,1i8a,1i8d,1i8f,1i8t,1i8v,1i94,1i" +
        "9c,1iam,1ib4,1ibd,1ibp,1ibw,1ibz,1ic0,1ic3,1ico,1icq,1icw,1icy,1icz,1id1,1id5,1id9,1id9,1ids,1ids,1i" +
        "e5,1ie9,1if4,1ifd,1iff,1iff,1ifi,1ifi,1ifk,1igl,1ign,1ign,1ihd,1ihd,1ihf,1ihf,1iio,1ik4,1ikn,1ikq,1i" +
        "kw,1il5,1ilb,1ild,1im8,1inj,1io4,1io5,1io7,1io7,1iog,1iop,1itc,1ium,1ivs,1ivv,1iww,1iy7,1iys,1iys,1i" +
        "z4,1izd,1j0g,1j1m,1j20,1j20,1j28,1j2h,1j2o,1j37,1j40,1j4q,1j5c,1j5n,1j5s,1j5y,1jb4,1jcb,1jfk,1jhu,1j" +
        "i7,1jie,1jih,1jih,1jik,1jir,1jit,1jiu,1jiw,1jjj,1jjz,1jjz,1jk1,1jk1,1jkg,1jkp,1jmo,1jmv,1jmy,1jo0,1j" +
        "oh,1joh,1joj,1joj,1jpc,1jpc,1jpn,1jqq,1jqy,1jqy,1jrk,1jrk,1jrw,1jt5,1jtp,1jtp,1ju8,1jw8,1k1s,1k2o,1k" +
        "34,1k3d,1k3k,1k3s,1k3u,1k4u,1k5c,1k5c,1k5s,1k6k,1k6q,1k7j,1kao,1kau,1kaw,1kax,1kaz,1kc0,1kcm,1kcm,1k" +
        "cw,1kd5,1kdc,1kdh,1kdj,1kdk,1kdm,1keh,1kew,1kew,1kf4,1kfd,1kfk,1kgr,1kgw,1kh5,1ko0,1koi,1koy,1koy,1k" +
        "p0,1kpc,1kpe,1kqb,1kr4,1krd,1kts,1kts,1ku8,1kus,1kw0,1lll,1log,1lri,1ls0,1lxf,1nyo,1o1c,1o1s,1ovj,1o" +
        "w1,1ow6,1oww,1rzu,1s00,1sg6,1xq8,1xr1,1xrk,1xrt,1z40,1zjs,1zk0,1zku,1zkw,1zl5,1zlc,1zni,1znk,1znt,1z" +
        "o0,1zot,1zpc,1zqn,1zr4,1zr7,1zrk,1zrt,1zrv,1zs1,1zs3,1zsn,1zst,1ztb,205c,206k,206o,206x,20cg,20eu,20" +
        "f4,20fs,20fv,20gj,20hs,20ju,20k0,20k0,20lv,20m7,20o0,20o1,20o3,20o3,20oi,20om,20ow,26dx,26f3,26fy,26" +
        "io,26lu,2dbk,2dbn,2dbp,2dbv,2dbx,2dby,2dc0,2dk2,2dki,2dki,2dlc,2dle,2dlh,2dlh,2dlw,2dlz,2dm8,2dx7,2f" +
        "pc,2fsa,2fsg,2fss,2fsw,2ft4,2ftc,2ftl,2j1s,2j21,2k74,2k7n,2k80,2k8j,2kbk,2kc8,2kg0,2kic,2kie,2kkc,2k" +
        "ke,2kkf,2kki,2kki,2kkl,2kkm,2kkp,2kks,2kku,2kl5,2kl7,2kl7,2kl9,2klf,2klh,2kn9,2knb,2kne,2knh,2kno,2k" +
        "nq,2knw,2kny,2kop,2kor,2kou,2kow,2kp0,2kp2,2kp2,2kp6,2kpc,2kpe,2kyt,2kyw,2kzk,2kzm,2l0a,2l0c,2l16,2l" +
        "18,2l1w,2l1y,2l2s,2l2u,2l3i,2l3k,2l4e,2l4g,2l54,2l56,2l60,2l62,2l6q,2l6s,2l6z,2l72,2l8f,2mm8,2mn2,2m" +
        "n9,2mne,2muo,2mwd,2n0g,2n1o,2n1z,2n25,2n28,2n2h,2n2m,2n2m,2nbk,2ncd,2ncw,2ne3,2ne8,2neh,2nrk,2nsb,2n" +
        "sg,2nsp,2nyo,2nzh,2nzk,2nzu,2o5c,2o66,2o68,2o6a,2o6c,2o6d,2o6f,2o6l,2o6o,2o6s,2o72,2o73,2odc,2odi,2o" +
        "dk,2odn,2odp,2odq,2ods,2oe6,2oe8,2ojo,2ojr,2ojz,2olc,2on7,2onf,2onf,2onk,2ont,2p9t,2pbf,2pbh,2pbj,2p" +
        "bl,2pbo,2pdt,2pf1,2pf3,2pfh,2pkw,2pkz,2pl1,2plr,2plt,2plu,2plw,2plw,2plz,2plz,2pm1,2pma,2pmc,2pmf,2p" +
        "mh,2pmh,2pmj,2pmj,2pmq,2pmq,2pmv,2pmv,2pmx,2pmx,2pmz,2pmz,2pn1,2pn3,2pn5,2pn6,2pn8,2pn8,2pnb,2pnb,2p" +
        "nd,2pnd,2pnf,2pnf,2pnh,2pnh,2pnj,2pnj,2pnl,2pnm,2pno,2pno,2pnr,2pnu,2pnw,2po2,2po4,2po7,2po9,2poc,2p" +
        "oe,2poe,2pog,2pop,2por,2pp7,2ppd,2ppf,2pph,2ppl,2ppn,2pq3,2q68,2q6k,2sc0,2sc9,2t4w,3q3j,3q4g,3ti5,3t" +
        "i8,3xyl,3xyo,43q8,43qo,447x,464g,46jh,47pc,4bii,4bio,4i2h",
    )

    /** Java isWhitespace || isSpaceChar, plus U+0085 (= Python str.isspace for our purposes): 10 ranges. */
    val SPACE: IntArray = decode(
        "9,d,s,w,3p,3p,4g,4g,4g0,4g0,6bk,6bu,6co,6cp,6cv,6cv,6e7,6e7,9hc,9hc",
    )

    private fun decode(s: String): IntArray = s.split(',').map { it.toInt(36) }.toIntArray()

    /** Binary search in a flattened range table. */
    fun contains(table: IntArray, cp: Int): Boolean {
        var lo = 0
        var hi = table.size / 2 - 1
        while (lo <= hi) {
            val mid = (lo + hi) ushr 1
            when {
                cp < table[2 * mid] -> hi = mid - 1
                cp > table[2 * mid + 1] -> lo = mid + 1
                else -> return true
            }
        }
        return false
    }
}
