import java.util.*;
import java.util.function.IntPredicate;
public class GenTables {
  static boolean word(int cp) {
    if (cp == '_') return true;
    switch (Character.getType(cp)) {
      case Character.UPPERCASE_LETTER: case Character.LOWERCASE_LETTER: case Character.TITLECASE_LETTER:
      case Character.MODIFIER_LETTER: case Character.OTHER_LETTER:
      case Character.DECIMAL_DIGIT_NUMBER: case Character.LETTER_NUMBER: case Character.OTHER_NUMBER: return true;
      default: return false;
    }
  }
  static boolean space(int cp) { return Character.isWhitespace(cp) || Character.isSpaceChar(cp) || cp == 0x85; }
  static List<Integer> ranges(IntPredicate p) {
    List<Integer> r = new ArrayList<>(); int start = -1;
    for (int cp = 0; cp <= 0x110000; cp++) {
      boolean in = cp <= 0x10FFFF && p.test(cp);
      if (in && start < 0) start = cp;
      if (!in && start >= 0) { r.add(start); r.add(cp - 1); start = -1; }
    }
    return r;
  }
  // Ranges as a string of base-36 numbers separated by ',' (compact and safe on every Kotlin backend).
  static String enc(List<Integer> r) { StringBuilder sb = new StringBuilder(); for (int v : r) { if (sb.length() > 0) sb.append(','); sb.append(Integer.toString(v, 36)); } return sb.toString(); }
  static void chunked(StringBuilder out, String s) {
    for (int i = 0; i < s.length(); i += 100) out.append("        \"").append(s, i, Math.min(s.length(), i + 100)).append("\" +\n");
    out.setLength(out.length() - 3); out.append(",\n");
  }
  public static void main(String[] a) {
    List<Integer> w = ranges(GenTables::word), s = ranges(GenTables::space);
    StringBuilder o = new StringBuilder();
    o.append("// GENERATED by scripts/GenTables.java from the JDK's Character data (JDK ")
     .append(System.getProperty("java.version")).append("). Do not edit.\n");
    o.append("package io.github.rajumark.hoverfly.moji.internal\n\n");
    o.append("/** Inclusive code point ranges, flattened [start0, end0, start1, end1, ...], base-36 encoded. */\n");
    o.append("internal object UnicodeTables {\n");
    o.append("    /** Letters (L*) and numbers (Nd, Nl, No), plus '_': ").append(w.size()/2).append(" ranges. */\n");
    o.append("    val WORD: IntArray = decode(\n"); chunked(o, enc(w)); o.append("    )\n\n");
    o.append("    /** Java isWhitespace || isSpaceChar, plus U+0085 (= Python str.isspace for our purposes): ").append(s.size()/2).append(" ranges. */\n");
    o.append("    val SPACE: IntArray = decode(\n"); chunked(o, enc(s)); o.append("    )\n\n");
    o.append("    private fun decode(s: String): IntArray = s.split(',').map { it.toInt(36) }.toIntArray()\n\n");
    o.append("    /** Binary search in a flattened range table. */\n");
    o.append("    fun contains(table: IntArray, cp: Int): Boolean {\n");
    o.append("        var lo = 0\n        var hi = table.size / 2 - 1\n");
    o.append("        while (lo <= hi) {\n            val mid = (lo + hi) ushr 1\n");
    o.append("            when {\n                cp < table[2 * mid] -> hi = mid - 1\n                cp > table[2 * mid + 1] -> lo = mid + 1\n                else -> return true\n            }\n        }\n        return false\n    }\n}\n");
    System.out.print(o);
  }
}
